import React, { useState } from "react";
import { Developer } from "./developer";
import "./_developers.scss";

export const Developers = () => {
  const [developers, setDevelopers] = useState(null);
  return (
    <div className="developers-wrapper">
      {DUMMY_DEVELOPERS.map((developer) => {
        return <Developer dev={developer} />;
      })}
    </div>
  );
};

export const DUMMY_DEVELOPERS = [
  {
    id: "0",
    firstName: "Rashad",
    middleName: "N",
    lastName: "Muhammad",
    skills: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "NodeJs",
      "Express",
      "Scala",
      "AWS",
      "Heroku",
    ],
    phone: "773-230-8360",
  },
  {
    id: "0",
    firstName: "Rashad",
    middleName: "N",
    lastName: "Muhammad",
    skills: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "NodeJs",
      "Express",
      "Scala",
      "AWS",
      "Heroku",
    ],
    phone: "773-230-8360",
  },
  {
    id: "0",
    firstName: "Rashad",
    middleName: "N",
    lastName: "Muhammad",
    skills: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "NodeJs",
      "Express",
      "Scala",
      "AWS",
      "Heroku",
    ],
    phone: "773-230-8360",
  },
  {
    id: "0",
    firstName: "Rashad",
    middleName: "N",
    lastName: "Muhammad",
    skills: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "NodeJs",
      "Express",
      "Scala",
      "AWS",
      "Heroku",
    ],
    phone: "773-230-8360",
  },
  {
    id: "0",
    firstName: "Rashad",
    middleName: "N",
    lastName: "Muhammad",
    skills: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "NodeJs",
      "Express",
      "Scala",
      "AWS",
      "Heroku",
    ],
    phone: "773-230-8360",
  },
  {
    id: "0",
    firstName: "Rashad",
    middleName: "N",
    lastName: "Muhammad",
    skills: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "NodeJs",
      "Express",
      "Scala",
      "AWS",
      "Heroku",
    ],
    phone: "773-230-8360",
  },
  {
    id: "0",
    firstName: "Rashad",
    middleName: "N",
    lastName: "Muhammad",
    skills: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "NodeJs",
      "Express",
      "Scala",
      "AWS",
      "Heroku",
    ],
    phone: "773-230-8360",
  },
  {
    id: "0",
    firstName: "Rashad",
    middleName: "N",
    lastName: "Muhammad",
    skills: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "NodeJs",
      "Express",
      "Scala",
      "AWS",
      "Heroku",
    ],
    phone: "773-230-8360",
  },
  {
    id: "0",
    firstName: "Rashad",
    middleName: "N",
    lastName: "Muhammad",
    skills: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "NodeJs",
      "Express",
      "Scala",
      "AWS",
      "Heroku",
    ],
    phone: "773-230-8360",
  },
  {
    id: "0",
    firstName: "Rashad",
    middleName: "N",
    lastName: "Muhammad",
    skills: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "NodeJs",
      "Express",
      "Scala",
      "AWS",
      "Heroku",
    ],
    phone: "773-230-8360",
  },
  {
    id: "0",
    firstName: "Rashad",
    middleName: "N",
    lastName: "Muhammad",
    skills: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "NodeJs",
      "Express",
      "Scala",
      "AWS",
      "Heroku",
    ],
    phone: "773-230-8360",
  },
  {
    id: "0",
    firstName: "Rashad",
    middleName: "N",
    lastName: "Muhammad",
    skills: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "NodeJs",
      "Express",
      "Scala",
      "AWS",
      "Heroku",
    ],
    phone: "773-230-8360",
  },
  {
    id: "0",
    firstName: "Rashad",
    middleName: "N",
    lastName: "Muhammad",
    skills: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "NodeJs",
      "Express",
      "Scala",
      "AWS",
      "Heroku",
    ],
    phone: "773-230-8360",
  },
];
